services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: wand
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wand_kb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://wand:postgres@db:5432/wand_kb
      DATA_DIR: /data
      INIT_DB: "true"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./data-backup:/data
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A celery_app worker --loglevel=debug -Q agents
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://wand:postgres@db:5432/wand_kb
      DATA_DIR: /data
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - api

volumes:
  pgdata: